import turtle

turtle.pencolor('black')
turtle.pensize(5)
turtle.fillcolor('Yellow')
turtle.begin_fill()
turtle.goto(0,100)
turtle.goto(-100,0)
turtle.goto(0,0)
turtle.end_fill()

turtle.fillcolor('Orange')
turtle.begin_fill()
turtle.goto(0,100)
turtle.goto(100,0)
turtle.goto(0,0)
turtle.end_fill()

turtle.fillcolor('Red')
turtle.begin_fill()
turtle.goto(100,0)
turtle.goto(0,-100)
turtle.goto(0,0)
turtle.end_fill()

turtle.fillcolor('green')
turtle.begin_fill()
turtle.goto(0,-100)
turtle.goto(-100,0)
turtle.goto(0,0)
turtle.end_fill()


turtle.goto(0,-100)
turtle.pencolor('red')
turtle.right(45)
turtle.forward(50)
turtle.goto(0,-100)
turtle.right(45)
turtle.forward(50)
turtle.goto(0,-100)
turtle.right(45)
turtle.forward(50)
turtle.done()

