
my_list = [5, 2, 9, 1]
my_list.append(4)
print("After Apend(): ", my_list)
print(my_list.count(2))
print(my_list.index(9))
print(my_list)
my_list.pop(1)
print(my_list)
my_list.insert(1, 10)
print(my_list)
my_list.remove(10)
print(my_list)
my_list.reverse()
print(my_list)
my_list.sort()
print(my_list)
